#-----------------------------------------------
# srclist.mk
# This file is automatically generated, don't try to edit it
# all modifications will be lost with next build
#-----------------------------------------------
ARCH := armv7
TARGET = AVD
BASEBOARD := G404
# Listing C/C++ source files here. (C dependencies are automatically generated.)
SRC += .\cgen\__GS_driverapi.c 
SRC += .\cgen\MCQ_dev.c 
SRC += .\cgen\RCColor.c 
SRC += .\cgen\RCText.c 
SRC += .\cgen\gdsPrjUserCInfo_CM.c 
SRC += .\cgen\gdsPrjUserCInfo_VR.c 
SRC += AVD.c 
SRC += mcm.c 
SRC += mask.c 
SRC += keyboard.c 
SRC += cycle.c 
SRC += init.c 
SRC += core.c 
# Debug options
FLAG_DEBUG = 0
FLAG_WINSIMU = 1
# Listing additional object files here.
ADDOBJ = 
LIBS = CanOpenSlaveStack-DSeriesS fpgaS iniS logS mbedcryptoS mbedtlsS mbedx509S mcmS gsNetwork-sslS gsThreadS UserCAPIS gsUtilS 
LIBDIRS = 
