/*******************************************************/
/*      This file is automatically generated           */
/*        !!! DO NOT MODIFY THIS FILE !!!              */
/*        All changes will be overwritten              */
/*******************************************************/

#ifndef _VARTAB_H_
#define _VARTAB_H_

/* Variable Table */
#define HDL_MASK_TASK_TURNOVER_TEXT 1            // Handle of MASK_TASK_TURNOVER_TEXT
#define IDX_MASK_TASK_TURNOVER_TEXT 0            // Index
#define HDL_MASK_TASK_PRESSURE_TEXT 2            // Handle of MASK_TASK_PRESSURE_TEXT
#define IDX_MASK_TASK_PRESSURE_TEXT 1            // Index
#define HDL_MASK_TASK_VALUES 3                   // Handle of MASK_TASK_VALUES
#define IDX_MASK_TASK_VALUES 2                   // Index
#define HDL_MASK_PASSWORD_NUMBER_ENTRY_1 4       // Handle of MASK_PASSWORD_NUMBER_ENTRY_1, Created by copy/paste object
#define IDX_MASK_PASSWORD_NUMBER_ENTRY_1 3       // Index
#define HDL_MASK_PASSWORD_NUMBER_ENTRY_2 5       // Handle of MASK_PASSWORD_NUMBER_ENTRY_2, Created by copy/paste object
#define IDX_MASK_PASSWORD_NUMBER_ENTRY_2 4       // Index
#define HDL_MASK_PASSWORD_NUMBER_ENTRY_3 6       // Handle of MASK_PASSWORD_NUMBER_ENTRY_3
#define IDX_MASK_PASSWORD_NUMBER_ENTRY_3 5       // Index
#define HDL_MASK_PASSWORD_NUMBER_ENTRY_4 7       // Handle of MASK_PASSWORD_NUMBER_ENTRY_4, Created by copy/paste object
#define IDX_MASK_PASSWORD_NUMBER_ENTRY_4 6       // Index
#define HDL_MASK_TASK_PRESSURE_TEXT_CENTER 8     // Handle of MASK_TASK_PRESSURE_TEXT_CENTER
#define IDX_MASK_TASK_PRESSURE_TEXT_CENTER 7     // Index
#define HDL_MASK_START_BEFORE_MAINTENANCE 9      // Handle of MASK_START_BEFORE_MAINTENANCE
#define IDX_MASK_START_BEFORE_MAINTENANCE 8      // Index
#define HDL_MASK_START_ENGINE_HOURS 10           // Handle of MASK_START_ENGINE_HOURS
#define IDX_MASK_START_ENGINE_HOURS 9            // Index
#define HDL_MASK_TASK_TURNOVER_TEXT_CENTER 11    // Handle of MASK_TASK_TURNOVER_TEXT_CENTER
#define IDX_MASK_TASK_TURNOVER_TEXT_CENTER 10    // Index
#define HDL_PRESSURE_OR_TURNOVER 12              // Handle of PRESSURE_OR_TURNOVER
#define IDX_PRESSURE_OR_TURNOVER 11              // Index
#define HDL_MASK_TASK_OUTLET_PRESSURE_MIN 14     // Handle of MASK_TASK_OUTLET_PRESSURE_MIN
#define IDX_MASK_TASK_OUTLET_PRESSURE_MIN 12     // Index
#define HDL_MASK_TASK_OUTLET_PRESSURE_MAX 15     // Handle of MASK_TASK_OUTLET_PRESSURE_MAX
#define IDX_MASK_TASK_OUTLET_PRESSURE_MAX 13     // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_1 16       // Handle of MASK_PUMP_SELECTED_OBJECT_1
#define IDX_MASK_PUMP_SELECTED_OBJECT_1 14       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_2 17       // Handle of MASK_PUMP_SELECTED_OBJECT_2
#define IDX_MASK_PUMP_SELECTED_OBJECT_2 15       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_3 18       // Handle of MASK_PUMP_SELECTED_OBJECT_3
#define IDX_MASK_PUMP_SELECTED_OBJECT_3 16       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_4 19       // Handle of MASK_PUMP_SELECTED_OBJECT_4
#define IDX_MASK_PUMP_SELECTED_OBJECT_4 17       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_5 20       // Handle of MASK_PUMP_SELECTED_OBJECT_5
#define IDX_MASK_PUMP_SELECTED_OBJECT_5 18       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_6 21       // Handle of MASK_PUMP_SELECTED_OBJECT_6
#define IDX_MASK_PUMP_SELECTED_OBJECT_6 19       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_7 22       // Handle of MASK_PUMP_SELECTED_OBJECT_7
#define IDX_MASK_PUMP_SELECTED_OBJECT_7 20       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_8 23       // Handle of MASK_PUMP_SELECTED_OBJECT_8
#define IDX_MASK_PUMP_SELECTED_OBJECT_8 21       // Index
#define HDL_MASK_PUMP_SELECTED_OBJECT_9 24       // Handle of MASK_PUMP_SELECTED_OBJECT_9
#define IDX_MASK_PUMP_SELECTED_OBJECT_9 22       // Index
#define HDL_OUTLET_PRESSURE 25                   // Handle of OUTLET_PRESSURE
#define IDX_OUTLET_PRESSURE 23                   // Index
#define HDL_ENGINE_SPEED 26                      // Handle of ENGINE_SPEED
#define IDX_ENGINE_SPEED 24                      // Index
#define HDL_ENGINE_LOAD 27                       // Handle of ENGINE_LOAD
#define IDX_ENGINE_LOAD 25                       // Index
#define HDL_INLET_PRESSURE 28                    // Handle of INLET_PRESSURE
#define IDX_INLET_PRESSURE 26                    // Index
#define HDL_INLET_WATER_TEMPERATURE 29           // Handle of INLET_WATER_TEMPERATURE
#define IDX_INLET_WATER_TEMPERATURE 27           // Index
#define HDL_ENGINE_OIL_PRESSURE 30               // Handle of ENGINE_OIL_PRESSURE
#define IDX_ENGINE_OIL_PRESSURE 28               // Index
#define HDL_ENGINE_OIL_TEMPERATURE 31            // Handle of ENGINE_OIL_TEMPERATURE
#define IDX_ENGINE_OIL_TEMPERATURE 29            // Index
#define HDL_ENGINE_OIL_LEVEL 32                  // Handle of ENGINE_OIL_LEVEL
#define IDX_ENGINE_OIL_LEVEL 30                  // Index
#define HDL_ENGINE_COOLANT_LEVEL 33              // Handle of ENGINE_COOLANT_LEVEL
#define IDX_ENGINE_COOLANT_LEVEL 31              // Index
#define HDL_ENGINE_COOLANT_TEMPERATURE 34        // Handle of ENGINE_COOLANT_TEMPERATURE
#define IDX_ENGINE_COOLANT_TEMPERATURE 32        // Index
#define HDL_FUEL_LEVEL 35                        // Handle of FUEL_LEVEL
#define IDX_FUEL_LEVEL 33                        // Index
#define HDL_NETWORK_VOLTAGE 36                   // Handle of NETWORK_VOLTAGE
#define IDX_NETWORK_VOLTAGE 34                   // Index
#define HDL_INSTANTANEOUS_FUEL_CONSUMPTION 37    // Handle of INSTANTANEOUS_FUEL_CONSUMPTION
#define IDX_INSTANTANEOUS_FUEL_CONSUMPTION 35    // Index
#define HDL_TOTAL_FUEL_CONSUMPTION 38            // Handle of TOTAL_FUEL_CONSUMPTION
#define IDX_TOTAL_FUEL_CONSUMPTION 36            // Index
#define HDL_ENGINE_HOURS 39                      // Handle of ENGINE_HOURS
#define IDX_ENGINE_HOURS 37                      // Index
#define HDL_GEARBOX_OIL_PRESSURE 40              // Handle of GEARBOX_OIL_PRESSURE
#define IDX_GEARBOX_OIL_PRESSURE 38              // Index
#define HDL_GEARBOX_OIL_TEMPERATURE 41           // Handle of GEARBOX_OIL_TEMPERATURE
#define IDX_GEARBOX_OIL_TEMPERATURE 39           // Index
#define HDL_FILTER_CLOGGING_LEVEL 42             // Handle of FILTER_CLOGGING_LEVEL
#define IDX_FILTER_CLOGGING_LEVEL 40             // Index
#define HDL_BEFORE_ENGINE_MAINTENANCE 43         // Handle of BEFORE_ENGINE_MAINTENANCE
#define IDX_BEFORE_ENGINE_MAINTENANCE 41         // Index
#define HDL_BEFORE_PUMP_MAINTENANCE 44           // Handle of BEFORE_PUMP_MAINTENANCE
#define IDX_BEFORE_PUMP_MAINTENANCE 42           // Index
#define HDL_WATER_LEVEL_IN_TANK 45               // Handle of WATER_LEVEL_IN_TANK
#define IDX_WATER_LEVEL_IN_TANK 43               // Index
#define HDL_MASK_PARAM1_VALUES 46                // Handle of MASK_PARAM1_VALUES, Created by copy/paste object
#define IDX_MASK_PARAM1_VALUES 44                // Index
#define HDL_MASK_PARAM2_VALUES 47                // Handle of MASK_PARAM2_VALUES, Created by copy/paste object
#define IDX_MASK_PARAM2_VALUES 45                // Index
#define HDL_MASK_PARAM3_VALUES 48                // Handle of MASK_PARAM3_VALUES, Created by copy/paste object
#define IDX_MASK_PARAM3_VALUES 46                // Index
#define HDL_MASK_PARAM4_VALUES 49                // Handle of MASK_PARAM4_VALUES, Created by copy/paste object
#define IDX_MASK_PARAM4_VALUES 47                // Index
#define HDL_MASK_PARAM5_VALUES 50                // Handle of MASK_PARAM5_VALUES, Created by copy/paste object
#define IDX_MASK_PARAM5_VALUES 48                // Index
#define HDL_MASK_PUMP_SELECTED_1 51              // Handle of MASK_PUMP_SELECTED_1
#define IDX_MASK_PUMP_SELECTED_1 49              // Index
#define HDL_MASK_PUMP_SELECTED_2 52              // Handle of MASK_PUMP_SELECTED_2
#define IDX_MASK_PUMP_SELECTED_2 50              // Index
#define HDL_MASK_PUMP_SELECTED_3 53              // Handle of MASK_PUMP_SELECTED_3
#define IDX_MASK_PUMP_SELECTED_3 51              // Index
#define HDL_MASK_PUMP_SELECTED_4 54              // Handle of MASK_PUMP_SELECTED_4
#define IDX_MASK_PUMP_SELECTED_4 52              // Index
#define HDL_MASK_PUMP_SELECTED_5 55              // Handle of MASK_PUMP_SELECTED_5
#define IDX_MASK_PUMP_SELECTED_5 53              // Index
#define HDL_MASK_PUMP_SELECTED_6 56              // Handle of MASK_PUMP_SELECTED_6
#define IDX_MASK_PUMP_SELECTED_6 54              // Index
#define HDL_MASK_PUMP_SELECTED_7 57              // Handle of MASK_PUMP_SELECTED_7
#define IDX_MASK_PUMP_SELECTED_7 55              // Index
#define HDL_MASK_PUMP_SELECTED_8 58              // Handle of MASK_PUMP_SELECTED_8
#define IDX_MASK_PUMP_SELECTED_8 56              // Index
#define HDL_MASK_PUMP_SELECTED_9 59              // Handle of MASK_PUMP_SELECTED_9
#define IDX_MASK_PUMP_SELECTED_9 57              // Index
#define HDL_MASK_ENGINE_SELECTED_OBJECT_1 100    // Handle of MASK_ENGINE_SELECTED_OBJECT_1
#define IDX_MASK_ENGINE_SELECTED_OBJECT_1 58     // Index
#define HDL_MASK_ENGINE_SELECTED_OBJECT_2 101    // Handle of MASK_ENGINE_SELECTED_OBJECT_2
#define IDX_MASK_ENGINE_SELECTED_OBJECT_2 59     // Index
#define HDL_MASK_ENGINE_SELECTED_OBJECT_3 102    // Handle of MASK_ENGINE_SELECTED_OBJECT_3
#define IDX_MASK_ENGINE_SELECTED_OBJECT_3 60     // Index
#define HDL_MASK_ENGINE_SELECTED_OBJECT_4 103    // Handle of MASK_ENGINE_SELECTED_OBJECT_4
#define IDX_MASK_ENGINE_SELECTED_OBJECT_4 61     // Index
#define HDL_MASK_ENGINE_SELECTED_OBJECT_5 104    // Handle of MASK_ENGINE_SELECTED_OBJECT_5
#define IDX_MASK_ENGINE_SELECTED_OBJECT_5 62     // Index
#define HDL_MASK_ENGINE_VALUE_1 105              // Handle of MASK_ENGINE_VALUE_1
#define IDX_MASK_ENGINE_VALUE_1 63               // Index
#define HDL_MASK_ENGINE_VALUE_2 106              // Handle of MASK_ENGINE_VALUE_2
#define IDX_MASK_ENGINE_VALUE_2 64               // Index
#define HDL_MASK_ENGINE_VALUE_3 107              // Handle of MASK_ENGINE_VALUE_3
#define IDX_MASK_ENGINE_VALUE_3 65               // Index
#define HDL_MASK_ENGINE_VALUE_4 108              // Handle of MASK_ENGINE_VALUE_4
#define IDX_MASK_ENGINE_VALUE_4 66               // Index
#define HDL_MASK_ENGINE_VALUE_5 109              // Handle of MASK_ENGINE_VALUE_5
#define IDX_MASK_ENGINE_VALUE_5 67               // Index
#define HDL_MASK_ENGINE_GREEN_1 110              // Handle of MASK_ENGINE_GREEN_1
#define IDX_MASK_ENGINE_GREEN_1 68               // Index
#define HDL_MASK_ENGINE_GREEN_2 111              // Handle of MASK_ENGINE_GREEN_2
#define IDX_MASK_ENGINE_GREEN_2 69               // Index
#define HDL_MASK_ENGINE_GREEN_3 112              // Handle of MASK_ENGINE_GREEN_3
#define IDX_MASK_ENGINE_GREEN_3 70               // Index
#define HDL_MASK_ENGINE_GREEN_4 113              // Handle of MASK_ENGINE_GREEN_4
#define IDX_MASK_ENGINE_GREEN_4 71               // Index
#define HDL_MASK_ENGINE_GREEN_5 114              // Handle of MASK_ENGINE_GREEN_5
#define IDX_MASK_ENGINE_GREEN_5 72               // Index
#define HDL_MASK_PUMP_OUTLET_PRESSURE_MIN 200    // Handle of MASK_PUMP_OUTLET_PRESSURE_MIN
#define IDX_MASK_PUMP_OUTLET_PRESSURE_MIN 73     // Index
#define HDL_MASK_PUMP_OUTLET_PRESSURE_MAX 201    // Handle of MASK_PUMP_OUTLET_PRESSURE_MAX
#define IDX_MASK_PUMP_OUTLET_PRESSURE_MAX 74     // Index
#define HDL_MASK_PUMP_INLET_PRESSURE_MIN 202     // Handle of MASK_PUMP_INLET_PRESSURE_MIN
#define IDX_MASK_PUMP_INLET_PRESSURE_MIN 75      // Index
#define HDL_MASK_PUMP_INLET_PRESSURE_MAX 203     // Handle of MASK_PUMP_INLET_PRESSURE_MAX
#define IDX_MASK_PUMP_INLET_PRESSURE_MAX 76      // Index
#define HDL_MASK_PUMP_WATER_TEMPERATURE_MIN 204  // Handle of MASK_PUMP_WATER_TEMPERATURE_MIN, Created by copy/paste object
#define IDX_MASK_PUMP_WATER_TEMPERATURE_MIN 77   // Index
#define HDL_MASK_PUMP_WATER_TEMPERATURE_MAX 205  // Handle of MASK_PUMP_WATER_TEMPERATURE_MAX
#define IDX_MASK_PUMP_WATER_TEMPERATURE_MAX 78   // Index
#define HDL_MASK_PUMP_OIL_TEMPERATURE_MAX 206    // Handle of MASK_PUMP_OIL_TEMPERATURE_MAX
#define IDX_MASK_PUMP_OIL_TEMPERATURE_MAX 79     // Index
#define HDL_MASK_PUMP_OIL_PRESSURE_MIN 207       // Handle of MASK_PUMP_OIL_PRESSURE_MIN
#define IDX_MASK_PUMP_OIL_PRESSURE_MIN 80        // Index
#define HDL_MASK_PUMP_OIL_PRESSURE_MAX 208       // Handle of MASK_PUMP_OIL_PRESSURE_MAX
#define IDX_MASK_PUMP_OIL_PRESSURE_MAX 81        // Index
#define HDL_MASK_TECHNICAL_VALUE_0 300           // Handle of MASK_TECHNICAL_VALUE_0
#define IDX_MASK_TECHNICAL_VALUE_0 82            // Index
#define HDL_MASK_TECHNICAL_VALUE_1 301           // Handle of MASK_TECHNICAL_VALUE_1
#define IDX_MASK_TECHNICAL_VALUE_1 83            // Index
#define HDL_MASK_TECHNICAL_VALUE_2 302           // Handle of MASK_TECHNICAL_VALUE_2
#define IDX_MASK_TECHNICAL_VALUE_2 84            // Index
#define HDL_MASK_TECHNICAL_VALUE_3 303           // Handle of MASK_TECHNICAL_VALUE_3
#define IDX_MASK_TECHNICAL_VALUE_3 85            // Index
#define HDL_MASK_TECHNICAL_GRAY_0 304            // Handle of MASK_TECHNICAL_GRAY_0
#define IDX_MASK_TECHNICAL_GRAY_0 86             // Index
#define HDL_MASK_TECHNICAL_GRAY_1 305            // Handle of MASK_TECHNICAL_GRAY_1
#define IDX_MASK_TECHNICAL_GRAY_1 87             // Index
#define HDL_MASK_TECHNICAL_GREEN_0 306           // Handle of MASK_TECHNICAL_GREEN_0
#define IDX_MASK_TECHNICAL_GREEN_0 88            // Index
#define HDL_MASK_TECHNICAL_GREEN_1 307           // Handle of MASK_TECHNICAL_GREEN_1
#define IDX_MASK_TECHNICAL_GREEN_1 89            // Index
#define HDL_SYS_U_SUPPLY 65524                   // Handle of SYS_U_SUPPLY
#define IDX_SYS_U_SUPPLY 90                      // Index
#define HDL_SYS_ENC_RIGHT 65525                  // Handle of SYS_ENC_RIGHT
#define IDX_SYS_ENC_RIGHT 91                     // Index
#define HDL_SYS_ENC_LEFT 65526                   // Handle of SYS_ENC_LEFT
#define IDX_SYS_ENC_LEFT 92                      // Index
#define HDL_SYS_TEMPERATURE 65527                // Handle of SYS_TEMPERATURE
#define IDX_SYS_TEMPERATURE 93                   // Index
#define HDL_SYS_PRIORITY 65528                   // Handle of SYS_PRIORITY
#define IDX_SYS_PRIORITY 94                      // Index
#define HDL_SYS_COLOR 65529                      // Handle of SYS_COLOR
#define IDX_SYS_COLOR 95                         // Index
#define HDL_SYS_LANGUAGE 65530                   // Handle of SYS_LANGUAGE
#define IDX_SYS_LANGUAGE 96                      // Index
#define HDL_SYS_OPERATING_TIME 65531             // Handle of SYS_OPERATING_TIME
#define IDX_SYS_OPERATING_TIME 97                // Index

/* Variable Groups */

/* Variable Table (old style) */
#ifdef USE_OLDSTYLE_VARIABLE_SYMBOLS
#define MASK_TASK_TURNOVER_TEXT 1               // Handle of MASK_TASK_TURNOVER_TEXT
#define MASK_TASK_TURNOVER_TEXT_idx 0           // Index
#define MASK_TASK_PRESSURE_TEXT 2               // Handle of MASK_TASK_PRESSURE_TEXT
#define MASK_TASK_PRESSURE_TEXT_idx 1           // Index
#define MASK_TASK_VALUES 3                      // Handle of MASK_TASK_VALUES
#define MASK_TASK_VALUES_idx 2                  // Index
#define MASK_PASSWORD_NUMBER_ENTRY_1 4          // Handle of MASK_PASSWORD_NUMBER_ENTRY_1, Created by copy/paste object
#define MASK_PASSWORD_NUMBER_ENTRY_1_idx 3      // Index
#define MASK_PASSWORD_NUMBER_ENTRY_2 5          // Handle of MASK_PASSWORD_NUMBER_ENTRY_2, Created by copy/paste object
#define MASK_PASSWORD_NUMBER_ENTRY_2_idx 4      // Index
#define MASK_PASSWORD_NUMBER_ENTRY_3 6          // Handle of MASK_PASSWORD_NUMBER_ENTRY_3
#define MASK_PASSWORD_NUMBER_ENTRY_3_idx 5      // Index
#define MASK_PASSWORD_NUMBER_ENTRY_4 7          // Handle of MASK_PASSWORD_NUMBER_ENTRY_4, Created by copy/paste object
#define MASK_PASSWORD_NUMBER_ENTRY_4_idx 6      // Index
#define MASK_TASK_PRESSURE_TEXT_CENTER 8        // Handle of MASK_TASK_PRESSURE_TEXT_CENTER
#define MASK_TASK_PRESSURE_TEXT_CENTER_idx 7    // Index
#define MASK_START_BEFORE_MAINTENANCE 9         // Handle of MASK_START_BEFORE_MAINTENANCE
#define MASK_START_BEFORE_MAINTENANCE_idx 8     // Index
#define MASK_START_ENGINE_HOURS 10              // Handle of MASK_START_ENGINE_HOURS
#define MASK_START_ENGINE_HOURS_idx 9           // Index
#define MASK_TASK_TURNOVER_TEXT_CENTER 11       // Handle of MASK_TASK_TURNOVER_TEXT_CENTER
#define MASK_TASK_TURNOVER_TEXT_CENTER_idx 10   // Index
#define PRESSURE_OR_TURNOVER 12                 // Handle of PRESSURE_OR_TURNOVER
#define PRESSURE_OR_TURNOVER_idx 11             // Index
#define MASK_TASK_OUTLET_PRESSURE_MIN 14        // Handle of MASK_TASK_OUTLET_PRESSURE_MIN
#define MASK_TASK_OUTLET_PRESSURE_MIN_idx 12    // Index
#define MASK_TASK_OUTLET_PRESSURE_MAX 15        // Handle of MASK_TASK_OUTLET_PRESSURE_MAX
#define MASK_TASK_OUTLET_PRESSURE_MAX_idx 13    // Index
#define MASK_PUMP_SELECTED_OBJECT_1 16          // Handle of MASK_PUMP_SELECTED_OBJECT_1
#define MASK_PUMP_SELECTED_OBJECT_1_idx 14      // Index
#define MASK_PUMP_SELECTED_OBJECT_2 17          // Handle of MASK_PUMP_SELECTED_OBJECT_2
#define MASK_PUMP_SELECTED_OBJECT_2_idx 15      // Index
#define MASK_PUMP_SELECTED_OBJECT_3 18          // Handle of MASK_PUMP_SELECTED_OBJECT_3
#define MASK_PUMP_SELECTED_OBJECT_3_idx 16      // Index
#define MASK_PUMP_SELECTED_OBJECT_4 19          // Handle of MASK_PUMP_SELECTED_OBJECT_4
#define MASK_PUMP_SELECTED_OBJECT_4_idx 17      // Index
#define MASK_PUMP_SELECTED_OBJECT_5 20          // Handle of MASK_PUMP_SELECTED_OBJECT_5
#define MASK_PUMP_SELECTED_OBJECT_5_idx 18      // Index
#define MASK_PUMP_SELECTED_OBJECT_6 21          // Handle of MASK_PUMP_SELECTED_OBJECT_6
#define MASK_PUMP_SELECTED_OBJECT_6_idx 19      // Index
#define MASK_PUMP_SELECTED_OBJECT_7 22          // Handle of MASK_PUMP_SELECTED_OBJECT_7
#define MASK_PUMP_SELECTED_OBJECT_7_idx 20      // Index
#define MASK_PUMP_SELECTED_OBJECT_8 23          // Handle of MASK_PUMP_SELECTED_OBJECT_8
#define MASK_PUMP_SELECTED_OBJECT_8_idx 21      // Index
#define MASK_PUMP_SELECTED_OBJECT_9 24          // Handle of MASK_PUMP_SELECTED_OBJECT_9
#define MASK_PUMP_SELECTED_OBJECT_9_idx 22      // Index
#define OUTLET_PRESSURE 25                      // Handle of OUTLET_PRESSURE
#define OUTLET_PRESSURE_idx 23                  // Index
#define ENGINE_SPEED 26                         // Handle of ENGINE_SPEED
#define ENGINE_SPEED_idx 24                     // Index
#define ENGINE_LOAD 27                          // Handle of ENGINE_LOAD
#define ENGINE_LOAD_idx 25                      // Index
#define INLET_PRESSURE 28                       // Handle of INLET_PRESSURE
#define INLET_PRESSURE_idx 26                   // Index
#define INLET_WATER_TEMPERATURE 29              // Handle of INLET_WATER_TEMPERATURE
#define INLET_WATER_TEMPERATURE_idx 27          // Index
#define ENGINE_OIL_PRESSURE 30                  // Handle of ENGINE_OIL_PRESSURE
#define ENGINE_OIL_PRESSURE_idx 28              // Index
#define ENGINE_OIL_TEMPERATURE 31               // Handle of ENGINE_OIL_TEMPERATURE
#define ENGINE_OIL_TEMPERATURE_idx 29           // Index
#define ENGINE_OIL_LEVEL 32                     // Handle of ENGINE_OIL_LEVEL
#define ENGINE_OIL_LEVEL_idx 30                 // Index
#define ENGINE_COOLANT_LEVEL 33                 // Handle of ENGINE_COOLANT_LEVEL
#define ENGINE_COOLANT_LEVEL_idx 31             // Index
#define ENGINE_COOLANT_TEMPERATURE 34           // Handle of ENGINE_COOLANT_TEMPERATURE
#define ENGINE_COOLANT_TEMPERATURE_idx 32       // Index
#define FUEL_LEVEL 35                           // Handle of FUEL_LEVEL
#define FUEL_LEVEL_idx 33                       // Index
#define NETWORK_VOLTAGE 36                      // Handle of NETWORK_VOLTAGE
#define NETWORK_VOLTAGE_idx 34                  // Index
#define INSTANTANEOUS_FUEL_CONSUMPTION 37       // Handle of INSTANTANEOUS_FUEL_CONSUMPTION
#define INSTANTANEOUS_FUEL_CONSUMPTION_idx 35   // Index
#define TOTAL_FUEL_CONSUMPTION 38               // Handle of TOTAL_FUEL_CONSUMPTION
#define TOTAL_FUEL_CONSUMPTION_idx 36           // Index
#define ENGINE_HOURS 39                         // Handle of ENGINE_HOURS
#define ENGINE_HOURS_idx 37                     // Index
#define GEARBOX_OIL_PRESSURE 40                 // Handle of GEARBOX_OIL_PRESSURE
#define GEARBOX_OIL_PRESSURE_idx 38             // Index
#define GEARBOX_OIL_TEMPERATURE 41              // Handle of GEARBOX_OIL_TEMPERATURE
#define GEARBOX_OIL_TEMPERATURE_idx 39          // Index
#define FILTER_CLOGGING_LEVEL 42                // Handle of FILTER_CLOGGING_LEVEL
#define FILTER_CLOGGING_LEVEL_idx 40            // Index
#define BEFORE_ENGINE_MAINTENANCE 43            // Handle of BEFORE_ENGINE_MAINTENANCE
#define BEFORE_ENGINE_MAINTENANCE_idx 41        // Index
#define BEFORE_PUMP_MAINTENANCE 44              // Handle of BEFORE_PUMP_MAINTENANCE
#define BEFORE_PUMP_MAINTENANCE_idx 42          // Index
#define WATER_LEVEL_IN_TANK 45                  // Handle of WATER_LEVEL_IN_TANK
#define WATER_LEVEL_IN_TANK_idx 43              // Index
#define MASK_PARAM1_VALUES 46                   // Handle of MASK_PARAM1_VALUES, Created by copy/paste object
#define MASK_PARAM1_VALUES_idx 44               // Index
#define MASK_PARAM2_VALUES 47                   // Handle of MASK_PARAM2_VALUES, Created by copy/paste object
#define MASK_PARAM2_VALUES_idx 45               // Index
#define MASK_PARAM3_VALUES 48                   // Handle of MASK_PARAM3_VALUES, Created by copy/paste object
#define MASK_PARAM3_VALUES_idx 46               // Index
#define MASK_PARAM4_VALUES 49                   // Handle of MASK_PARAM4_VALUES, Created by copy/paste object
#define MASK_PARAM4_VALUES_idx 47               // Index
#define MASK_PARAM5_VALUES 50                   // Handle of MASK_PARAM5_VALUES, Created by copy/paste object
#define MASK_PARAM5_VALUES_idx 48               // Index
#define MASK_PUMP_SELECTED_1 51                 // Handle of MASK_PUMP_SELECTED_1
#define MASK_PUMP_SELECTED_1_idx 49             // Index
#define MASK_PUMP_SELECTED_2 52                 // Handle of MASK_PUMP_SELECTED_2
#define MASK_PUMP_SELECTED_2_idx 50             // Index
#define MASK_PUMP_SELECTED_3 53                 // Handle of MASK_PUMP_SELECTED_3
#define MASK_PUMP_SELECTED_3_idx 51             // Index
#define MASK_PUMP_SELECTED_4 54                 // Handle of MASK_PUMP_SELECTED_4
#define MASK_PUMP_SELECTED_4_idx 52             // Index
#define MASK_PUMP_SELECTED_5 55                 // Handle of MASK_PUMP_SELECTED_5
#define MASK_PUMP_SELECTED_5_idx 53             // Index
#define MASK_PUMP_SELECTED_6 56                 // Handle of MASK_PUMP_SELECTED_6
#define MASK_PUMP_SELECTED_6_idx 54             // Index
#define MASK_PUMP_SELECTED_7 57                 // Handle of MASK_PUMP_SELECTED_7
#define MASK_PUMP_SELECTED_7_idx 55             // Index
#define MASK_PUMP_SELECTED_8 58                 // Handle of MASK_PUMP_SELECTED_8
#define MASK_PUMP_SELECTED_8_idx 56             // Index
#define MASK_PUMP_SELECTED_9 59                 // Handle of MASK_PUMP_SELECTED_9
#define MASK_PUMP_SELECTED_9_idx 57             // Index
#define MASK_ENGINE_SELECTED_OBJECT_1 100       // Handle of MASK_ENGINE_SELECTED_OBJECT_1
#define MASK_ENGINE_SELECTED_OBJECT_1_idx 58    // Index
#define MASK_ENGINE_SELECTED_OBJECT_2 101       // Handle of MASK_ENGINE_SELECTED_OBJECT_2
#define MASK_ENGINE_SELECTED_OBJECT_2_idx 59    // Index
#define MASK_ENGINE_SELECTED_OBJECT_3 102       // Handle of MASK_ENGINE_SELECTED_OBJECT_3
#define MASK_ENGINE_SELECTED_OBJECT_3_idx 60    // Index
#define MASK_ENGINE_SELECTED_OBJECT_4 103       // Handle of MASK_ENGINE_SELECTED_OBJECT_4
#define MASK_ENGINE_SELECTED_OBJECT_4_idx 61    // Index
#define MASK_ENGINE_SELECTED_OBJECT_5 104       // Handle of MASK_ENGINE_SELECTED_OBJECT_5
#define MASK_ENGINE_SELECTED_OBJECT_5_idx 62    // Index
#define MASK_ENGINE_VALUE_1 105                 // Handle of MASK_ENGINE_VALUE_1
#define MASK_ENGINE_VALUE_1_idx 63              // Index
#define MASK_ENGINE_VALUE_2 106                 // Handle of MASK_ENGINE_VALUE_2
#define MASK_ENGINE_VALUE_2_idx 64              // Index
#define MASK_ENGINE_VALUE_3 107                 // Handle of MASK_ENGINE_VALUE_3
#define MASK_ENGINE_VALUE_3_idx 65              // Index
#define MASK_ENGINE_VALUE_4 108                 // Handle of MASK_ENGINE_VALUE_4
#define MASK_ENGINE_VALUE_4_idx 66              // Index
#define MASK_ENGINE_VALUE_5 109                 // Handle of MASK_ENGINE_VALUE_5
#define MASK_ENGINE_VALUE_5_idx 67              // Index
#define MASK_ENGINE_GREEN_1 110                 // Handle of MASK_ENGINE_GREEN_1
#define MASK_ENGINE_GREEN_1_idx 68              // Index
#define MASK_ENGINE_GREEN_2 111                 // Handle of MASK_ENGINE_GREEN_2
#define MASK_ENGINE_GREEN_2_idx 69              // Index
#define MASK_ENGINE_GREEN_3 112                 // Handle of MASK_ENGINE_GREEN_3
#define MASK_ENGINE_GREEN_3_idx 70              // Index
#define MASK_ENGINE_GREEN_4 113                 // Handle of MASK_ENGINE_GREEN_4
#define MASK_ENGINE_GREEN_4_idx 71              // Index
#define MASK_ENGINE_GREEN_5 114                 // Handle of MASK_ENGINE_GREEN_5
#define MASK_ENGINE_GREEN_5_idx 72              // Index
#define MASK_PUMP_OUTLET_PRESSURE_MIN 200       // Handle of MASK_PUMP_OUTLET_PRESSURE_MIN
#define MASK_PUMP_OUTLET_PRESSURE_MIN_idx 73    // Index
#define MASK_PUMP_OUTLET_PRESSURE_MAX 201       // Handle of MASK_PUMP_OUTLET_PRESSURE_MAX
#define MASK_PUMP_OUTLET_PRESSURE_MAX_idx 74    // Index
#define MASK_PUMP_INLET_PRESSURE_MIN 202        // Handle of MASK_PUMP_INLET_PRESSURE_MIN
#define MASK_PUMP_INLET_PRESSURE_MIN_idx 75     // Index
#define MASK_PUMP_INLET_PRESSURE_MAX 203        // Handle of MASK_PUMP_INLET_PRESSURE_MAX
#define MASK_PUMP_INLET_PRESSURE_MAX_idx 76     // Index
#define MASK_PUMP_WATER_TEMPERATURE_MIN 204     // Handle of MASK_PUMP_WATER_TEMPERATURE_MIN, Created by copy/paste object
#define MASK_PUMP_WATER_TEMPERATURE_MIN_idx 77  // Index
#define MASK_PUMP_WATER_TEMPERATURE_MAX 205     // Handle of MASK_PUMP_WATER_TEMPERATURE_MAX
#define MASK_PUMP_WATER_TEMPERATURE_MAX_idx 78  // Index
#define MASK_PUMP_OIL_TEMPERATURE_MAX 206       // Handle of MASK_PUMP_OIL_TEMPERATURE_MAX
#define MASK_PUMP_OIL_TEMPERATURE_MAX_idx 79    // Index
#define MASK_PUMP_OIL_PRESSURE_MIN 207          // Handle of MASK_PUMP_OIL_PRESSURE_MIN
#define MASK_PUMP_OIL_PRESSURE_MIN_idx 80       // Index
#define MASK_PUMP_OIL_PRESSURE_MAX 208          // Handle of MASK_PUMP_OIL_PRESSURE_MAX
#define MASK_PUMP_OIL_PRESSURE_MAX_idx 81       // Index
#define MASK_TECHNICAL_VALUE_0 300              // Handle of MASK_TECHNICAL_VALUE_0
#define MASK_TECHNICAL_VALUE_0_idx 82           // Index
#define MASK_TECHNICAL_VALUE_1 301              // Handle of MASK_TECHNICAL_VALUE_1
#define MASK_TECHNICAL_VALUE_1_idx 83           // Index
#define MASK_TECHNICAL_VALUE_2 302              // Handle of MASK_TECHNICAL_VALUE_2
#define MASK_TECHNICAL_VALUE_2_idx 84           // Index
#define MASK_TECHNICAL_VALUE_3 303              // Handle of MASK_TECHNICAL_VALUE_3
#define MASK_TECHNICAL_VALUE_3_idx 85           // Index
#define MASK_TECHNICAL_GRAY_0 304               // Handle of MASK_TECHNICAL_GRAY_0
#define MASK_TECHNICAL_GRAY_0_idx 86            // Index
#define MASK_TECHNICAL_GRAY_1 305               // Handle of MASK_TECHNICAL_GRAY_1
#define MASK_TECHNICAL_GRAY_1_idx 87            // Index
#define MASK_TECHNICAL_GREEN_0 306              // Handle of MASK_TECHNICAL_GREEN_0
#define MASK_TECHNICAL_GREEN_0_idx 88           // Index
#define MASK_TECHNICAL_GREEN_1 307              // Handle of MASK_TECHNICAL_GREEN_1
#define MASK_TECHNICAL_GREEN_1_idx 89           // Index
#define SYS_U_SUPPLY 65524                      // Handle of SYS_U_SUPPLY
#define SYS_U_SUPPLY_idx 90                     // Index
#define SYS_ENC_RIGHT 65525                     // Handle of SYS_ENC_RIGHT
#define SYS_ENC_RIGHT_idx 91                    // Index
#define SYS_ENC_LEFT 65526                      // Handle of SYS_ENC_LEFT
#define SYS_ENC_LEFT_idx 92                     // Index
#define SYS_TEMPERATURE 65527                   // Handle of SYS_TEMPERATURE
#define SYS_TEMPERATURE_idx 93                  // Index
#define SYS_PRIORITY 65528                      // Handle of SYS_PRIORITY
#define SYS_PRIORITY_idx 94                     // Index
#define SYS_COLOR 65529                         // Handle of SYS_COLOR
#define SYS_COLOR_idx 95                        // Index
#define SYS_LANGUAGE 65530                      // Handle of SYS_LANGUAGE
#define SYS_LANGUAGE_idx 96                     // Index
#define SYS_OPERATING_TIME 65531                // Handle of SYS_OPERATING_TIME
#define SYS_OPERATING_TIME_idx 97               // Index
#undef USE_OLDSTYLE_VARIABLE_SYMBOLS
#endif

#endif
