#ifndef GSOSQVERSION_H_INCLUDED
#define GSOSQVERSION_H_INCLUDED
#define GSOSQVERSION_STR        "OS023S00"
#define GSOSQVERSION_MAIN       23
#define GSOSQVERSION_SUB        0
#define GSOSQVERSION_BETA       0
#define GSOSQVERSION_DAILY      0
#define GSOSQVERSION_TIMESTAMP  1607931175
#endif /* GSOSQVERSION_H_INCLUDED */
