/**-----------------------------------------------
 * __gs_PluginNames.h
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

extern char __gs_ExportedPlugins[];

