/**-----------------------------------------------
 * __gs_PluginNames.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

const char __gs_ExportedPlugins[] =
  "ATBargraph.\r\n"
  "ATIndexBitmap.\r\n"
  "ATResTTText.\r\n"
  "ATSimpleBitmap.\r\n"
  "ATTrueTypeText.\r\n"
  "ATTrueTypeVariable.\r\n"
  "ATQuad.\r\n";
