
/**-----------------------------------------------
 * __gs_gds_visu_data.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

#include <stdint.h>

typedef int32_t tObjNum;
typedef struct tagVisMaskColorTabEntry
{
  tObjNum  Number;  // Container or Mask number
  uint16_t BkColorNameIdx;
  uint16_t FrColorNameIdx;
  uint32_t Transparent;
}tVisMaskColorTabEntry;

const uint32_t _gs_ColorTableOffset = 512;
const uint32_t _gs_ContainerCnt = 0;
const uint32_t _gs_MaskCnt = 11;

const tVisMaskColorTabEntry _gs_visMaskColorTab[] =
{
  //  Co/Ma  BkColor  FrColor  Trans-
  // Number, NameIdx, NameIdx, parent
          7,   65535,   65535,     0,  // mask: Task
          6,   65535,   65535,     0,  // mask: UnicIdentificator
          0,   65535,   65535,     0,  // mask: Workspace
          1,   65535,   65535,     0,  // mask: Password
          2,   65535,   65535,     0,  // mask: Engine
          3,   65535,   65535,     0,  // mask: Pump
          4,   65535,   65535,     0,  // mask: Errors
          5,   65535,   65535,     0,  // mask: Parameters
          8,   65535,   65535,     0,  // mask: Menu
          9,   65535,   65535,     0,  // mask: Settings
         10,   65535,   65535,     0   // mask: Technical
};

