
/**-----------------------------------------------
 * ATTrendWriter.h
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next project saving
 **-----------------------------------------------*/

#ifndef _ATTRENDWRITER_H_
#define _ATTRENDWRITER_H_


#endif  //_ATTRENDWRITER_H_

