/**-----------------------------------------------
 * gdsPrjUserCInfo_CM.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

#include <gdsPrjUserCInfo.h>

/* ----- Container info ----- */
const tGsContInfo _gs_prjusercinfo_mContInfo[] =
{
    {.mName = "", .mNumber = 0}
};
const size_t _gs_prjusercinfo_mContInfoSize = 0;

/* ----- Mask info ----- */
const tGsMaskInfo _gs_prjusercinfo_mMaskInfo[] =
{
    {.mName = "Task", .mNumber = 7},
    {.mName = "UnicIdentificator", .mNumber = 6},
    {.mName = "Workspace", .mNumber = 0},
    {.mName = "Password", .mNumber = 1},
    {.mName = "Engine", .mNumber = 2},
    {.mName = "Pump", .mNumber = 3},
    {.mName = "Errors", .mNumber = 4},
    {.mName = "Parameters", .mNumber = 5},
    {.mName = "Menu", .mNumber = 8},
    {.mName = "Settings", .mNumber = 9},
    {.mName = "Technical", .mNumber = 10}
};
const size_t _gs_prjusercinfo_mMaskInfoSize = 11;

