
/*****************************************************************************
 * File:  OSVersion.h
 * 
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next build
 * 
 * Description:  Three defines for used OS version
 * 
 ****************************************************************************/

#ifndef _OSVERSION_H_
  #define _OSVERSION_H_

#define GS_OSVERS_MAJOR 23
#define GS_OSVERS_SUB   0
#define GS_OSVERS_BETA  0

#endif  //_OSVERSION_H_

