
/**-----------------------------------------------
 * RCColor.h
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with changing color resource

 * for access to color schemes use the symbols
 * only. Do not use the magic numbers !
 * The defines may change on designer configurations
 **-----------------------------------------------*/

#ifndef _RCCOLOR_H_
#define _RCCOLOR_H_

#include <stdint.h>

#define RCCOLOR_MAX_SCHEMES 0
#define RCCOLOR_MAX_NAMES 0



#ifdef __cplusplus
extern "C"
{
#endif

/**-----------------------------------------------
 * RCColorGetColor
 * Retrieves a color from color resource
 * @param cSchemeID: Scheme index
 * @param cNameID:   Color index
 * @return:          Color value
 *------------------------------------------------*/
uint32_t RCColorGetColor(uint16_t cSchemeID, uint16_t cNameID);

/**-----------------------------------------------
 * RCColorSetColor
 * Sets a color in color resource
 * @param cSchemeID: Scheme index
 * @param cNameID:   Color index
 * @param c:         Color value
 * @return:          -
 *------------------------------------------------*/
void RCColorSetColor(uint16_t cSchemeID, uint16_t cNameID, uint32_t c);

#ifdef __cplusplus
}
#endif

#endif  //_RCCOLOR_H_

