
/**-----------------------------------------------
 * RCText.h
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next project saving
 *
 * for access to texts from this resource use the symbols
 * only. Do not use the magic numbers !
 * The defines are changed to the resource base address at download
 *
 * Note: To use these 2 functions you have to check "Transfer all texts"
 *       in "Edit / Setup" in Text-Resourec-Dialog and to include
 *       "RCText.h" in your C-file!
 **-----------------------------------------------*/

#ifndef _RCTEXT_H_
#define _RCTEXT_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

/**-----------------------------------------------
 * RCTextGetText
 *
 * Retrieves a text from the text resource
 *
 * @param offset:  offset into the resource text table. Use offset
 *                 symbols "RCTEXT_T_..." from below to access
 * @param lngIdx:  Language index
 *                 Use GetVar(HDL_SYS_LANGUAGE) here
 *------------------------------------------------*/
const char* RCTextGetText(uint32_t offset, uint32_t lngIdx);

#ifdef __cplusplus
}
#endif

#define RCTEXT_CNT_G 11  // groups
#define RCTEXT_CNT_GT_START 6  // group texts
#define RCTEXT_CNT_GT_PASSWORD 2  // group texts
#define RCTEXT_CNT_GT_ENGINE 7  // group texts
#define RCTEXT_CNT_GT_AVD 7  // group texts
#define RCTEXT_CNT_GT_WORKSPACE 3  // group texts
#define RCTEXT_CNT_GT_ERRORS 2  // group texts
#define RCTEXT_CNT_GT_TASK 8  // group texts
#define RCTEXT_CNT_GT_MENU 5  // group texts
#define RCTEXT_CNT_GT_SETTINGS 3  // group texts
#define RCTEXT_CNT_GT_PARAMETERS 23  // group texts
#define RCTEXT_CNT_GT_TECHNICAL 7  // group texts
#define RCTEXT_CNT_T 73  // texts (all together)
#define RCTEXT_CNT_L 0  // lists

/*
  Now the offsets to be used for above functions
  RCTextGetText(..) and RCTextGetListElement(..)
*/
#define RCTEXT_T_BEFOREENGINEMAINTENANCE 4244		// BeforeEngineMaintenance (Parameters)
#define RCTEXT_T_BEFOREMAINTENANCE 624		// BeforeMaintenance (Start)
#define RCTEXT_T_BEFOREMAINTENANCEENGINE 792		// BeforeMaintenanceEngine (Start)
#define RCTEXT_T_BEFOREPUMPMAINTENANCE 4312		// BeforePumpMaintenance (Parameters)
#define RCTEXT_T_CANCEL 916		// Cancel (Password)
#define RCTEXT_T_CANCEL_ 2128		// Cancel (Task)
#define RCTEXT_T_CONTINUE 720		// Continue (Start)
#define RCTEXT_T_ENGINECOOLANTLEVEL 3492		// EngineCoolantLevel (Parameters)
#define RCTEXT_T_ENGINECOOLANTTEMPERATURE 3564		// EngineCoolantTemperature (Parameters)
#define RCTEXT_T_ENGINEHOURS 580		// EngineHours (Start)
#define RCTEXT_T_ENGINEHOURS_ 3936		// EngineHours (Parameters)
#define RCTEXT_T_ENGINELOAD 3036		// EngineLoad (Parameters)
#define RCTEXT_T_ENGINEMAINTENANCE 4528		// EngineMaintenance (Technical)
#define RCTEXT_T_ENGINEOILLEVEL 3416		// EngineOilLevel (Parameters)
#define RCTEXT_T_ENGINEOILPRESSURE 3336		// EngineOilPressure (Parameters)
#define RCTEXT_T_ENGINEOILTEMPERATURE 3248		// EngineOilTemperature (Parameters)
#define RCTEXT_T_ENGINERESET 4700		// EngineReset (Technical)
#define RCTEXT_T_ENGINESPEED 1072		// EngineSpeed (Engine)
#define RCTEXT_T_ENGINESPEED_ 2976		// EngineSpeed (Parameters)
#define RCTEXT_T_FILTERCLOGGINGLEVEL 4160		// FilterCloggingLevel (Parameters)
#define RCTEXT_T_FUELLEVEL 3652		// FuelLevel (Parameters)
#define RCTEXT_T_GEARBOXOILPRESSURE 3980		// GearboxOilPressure (Parameters)
#define RCTEXT_T_GEARBOXOILTEMPERATURE 4064		// GearboxOilTemperature (Parameters)
#define RCTEXT_T_INLETPRESSURE 1576		// InletPressure (Avd)
#define RCTEXT_T_INLETPRESSURE_ 3104		// InletPressure (Parameters)
#define RCTEXT_T_INLETWATERTEMPERATURE 3164		// InletWaterTemperature (Parameters)
#define RCTEXT_T_INSTANTANEOUSFUELCONSUMPTION 3768		// InstantaneousFuelConsumption (Parameters)
#define RCTEXT_T_JOURNAL 2636		// Journal (Menu)
#define RCTEXT_T_LANGUAGE 684		// Language (Start)
#define RCTEXT_T_LAST 4664		// Last (Technical)
#define RCTEXT_T_MAINWINDOW 4448		// MainWindow (Parameters)
#define RCTEXT_T_MAXIMUMTORQUE 1132		// MaximumTorque (Engine)
#define RCTEXT_T_MENU 1980		// Menu (Workspace)
#define RCTEXT_T_MINIMUMFUELLEVEL 1200		// MinimumFuelLevel (Engine)
#define RCTEXT_T_MINIMUMLEVELCOOLEDLIQUID 1340		// MinimumLevelCooledLiquid (Engine)
#define RCTEXT_T_MINIMUMOILLEVEL 1272		// MinimumOilLevel (Engine)
#define RCTEXT_T_MODE 1952		// Mode (Workspace)
#define RCTEXT_T_NETWORKVOLTAGE 3708		// NetworkVoltage (Parameters)
#define RCTEXT_T_NOTIFICATION 512		// Notification (Start)
#define RCTEXT_T_NOTIFICATIONS 944		// Notifications (Engine)
#define RCTEXT_T_NOTIFICATION_ 1452		// Notification (Avd)
#define RCTEXT_T_NOTIFICATION__ 1888		// Notification (Workspace)
#define RCTEXT_T_NOTIFICATION___ 2008		// Notification (Errors)
#define RCTEXT_T_NOTIFICATION____ 2500		// Notification (Menu)
#define RCTEXT_T_NOTIFICATION_____ 2720		// Notification (Settings)
#define RCTEXT_T_NOTIFICATION______ 2868		// Notification (Parameters)
#define RCTEXT_T_NOTIFICATION_______ 4476		// Notification (Technical)
#define RCTEXT_T_NOTOFICATION 2076		// Notofication (Task)
#define RCTEXT_T_OILPRESSURE 1764		// OilPressure (Avd)
#define RCTEXT_T_OILTEMPERATURE 1700		// OilTemperature (Avd)
#define RCTEXT_T_OUTLETPRESSURE 1512		// OutletPressure (Avd)
#define RCTEXT_T_OUTLETPRESSURE_ 2912		// OutletPressure (Parameters)
#define RCTEXT_T_PARAMETERS 2588		// Parameters (Menu)
#define RCTEXT_T_PASSWORD 860		// Password (Password)
#define RCTEXT_T_PERIOD 2772		// Period (Settings)
#define RCTEXT_T_PERIOD_ 4632		// Period (Technical)
#define RCTEXT_T_PRESSURE 2208		// Pressure (Task)
#define RCTEXT_T_PRESSURETEXT 2260		// PressureText (Task)
#define RCTEXT_T_PUMPMAINTENANCE 4584		// PumpMaintenance (Technical)
#define RCTEXT_T_PUMPRESET 4780		// PumpReset (Technical)
#define RCTEXT_T_REVOLUTIONS 2312		// Revolutions (Task)
#define RCTEXT_T_SCROLL 2040		// Scroll (Errors)
#define RCTEXT_T_SETTINGS 1012		// Settings (Engine)
#define RCTEXT_T_SETTINGS_ 1820		// Settings (Avd)
#define RCTEXT_T_SETTINGS__ 2676		// Settings (Menu)
#define RCTEXT_T_SETTINGS___ 2824		// Settings (Settings)
#define RCTEXT_T_TASK 2548		// Task (Menu)
#define RCTEXT_T_TOTALFUELCONSUMPTION 3860		// TotalFuelConsumption (Parameters)
#define RCTEXT_T_TURNOVER 2156		// Turnover (Task)
#define RCTEXT_T_VALUEMAX 2432		// ValueMax (Task)
#define RCTEXT_T_VALUEMIN 2364		// ValueMin (Task)
#define RCTEXT_T_WATERLEVELINTHETANK 4372		// WaterLevelInTheTank (Parameters)
#define RCTEXT_T_WATERTEMPERATURE 1636		// WaterTemperature (Avd)

#endif  //_RCTEXT_H_

