/*****************************************************************************
 * File:  TRJ1939_msg.c
 * 
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next build
 * 
 * Description:  description
 * 
 ****************************************************************************/

 /* e m p t y   f i l e */
 /* nothing to generate */


#include <UserCEvents.h>

// cppcheck-suppress unusedFunction
void _gs_event_trj1939_preinit(void)
{
}
// cppcheck-suppress unusedFunction
void _gs_event_trj1939_thrinit(void)
{
}
// cppcheck-suppress unusedFunction
void _gs_event_trj1939_deinit(void)
{
}
// cppcheck-suppress unusedFunction
void _gs_event_trj1939_cycle(uint32_t evtc, tUserCEvt * evtv)
{
}
// cppcheck-suppress unusedFunction
int32_t _gs_event_trj1939_event(uint32_t evtc, tUserCEvt * evtv)
{
  return 0;
}
