/*****************************************************************************
 * File:  TRJ1939_msg.h
 * 
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next build
 * 
 * Description:  description
 * 
 ****************************************************************************/

#ifndef _TRJ1939_MSG_H_
#define _TRJ1939_MSG_H_

 /* e m p t y   f i l e */
 /* nothing to generate */

#endif  //_TRJ1939_MSG_H_

