/*****************************************************************************
 * File:  TRModbusSlave_msg.h
 * 
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next build
 * 
 * Description:  description
 * 
 ****************************************************************************/

#ifndef _TRMODBUSSLAVE_MSG_H_
#define _TRMODBUSSLAVE_MSG_H_

/* === ModBusSlavePreMapping === */

/* Holding Registers: */

#define GS_MBSPM_MASK_ON_MSB                           0  
#define GS_MBSPM_MASK_ON_LSB                           1  
#define GS_MBSPM_MASK_OFF_MSB                          2  
#define GS_MBSPM_MASK_OFF_LSB                          3  
#define GS_MBSPM_PRIOMASK_ON_MSB                       4  
#define GS_MBSPM_PRIOMASK_ON_LSB                       5  
#define GS_MBSPM_MASK_NUMBER_MSB                       6  
#define GS_MBSPM_MASK_NUMBER_LSB                       7  
#define GS__BSPM_IS_MASK_ON                            8  /* mirror for write/read */
#define GS__BSPM_GET_CURRENT_MASK_SHOWN_MSB            9  /* mirror for write/read */
#define GS__BSPM_GET_CURRENT_MASK_SHOWN_LSB           10  /* mirror for write/read */

#define GS_MBSPM_INFO_CONTAINER_ON_MSB                20  
#define GS_MBSPM_INFO_CONTAINER_ON_LSB                21  
#define GS_MBSPM_INFO_CONTAINER_OFF_MSB               22  
#define GS_MBSPM_INFO_CONTAINER_OFF_LSB               23  
#define GS_MBSPM_INFO_CONTAINER_NUMBER_MSB            24  
#define GS_MBSPM_INFO_CONTAINER_NUMBER_LSB            25  
#define GS__BSPM_IS_INFO_CONTAINER_ON                 26  /* mirror for write/read */
#define GS_MBSPM_MSG_CONTAINER_ON_MSB                 27  
#define GS_MBSPM_MSG_CONTAINER_ON_LSB                 28  
#define GS_MBSPM_MSG_CONTAINER_OFF_MSB                29  
#define GS_MBSPM_MSG_CONTAINER_OFF_LSB                30  
#define GS_MBSPM_MSG_CONTAINER_NUMBER_MSB             31  
#define GS_MBSPM_MSG_CONTAINER_NUMBER_LSB             32  
#define GS__BSPM_IS_MSG_CONTAINER_ON                  33  /* mirror for write/read */
#define GS__BSPM_GET_CURRENT_MSG_CONTAINER_SHOWN_MSB  34  /* mirror for write/read */
#define GS__BSPM_GET_CURRENT_MSG_CONTAINER_SHOWN_LSB  35  /* mirror for write/read */

#define GS_MBSPM_SEND_KEY_MSB                         40  
#define GS_MBSPM_SEND_KEY_LSB                         41  
#define GS_MBSPM_SEND_KEY_TO_VISU_MSB                 42  
#define GS_MBSPM_SEND_KEY_TO_VISU_LSB                 43  
#define GS_MBSPM_KEY_CODE_MSB                         44  
#define GS_MBSPM_KEY_CODE_LSB                         45  
#define GS__BSPM_IS_KEY_DOWN                          46  /* mirror for write/read */
#define GS__BSPM_IS_ANY_KEY_DOWN                      47  /* mirror for write/read */

#define GS_MBSPM_SET_VAR_16_HANDLE_MSB                60  
#define GS_MBSPM_SET_VAR_16_HANDLE_LSB                61  
#define GS_MBSPM_SET_VAR_16_VAL                       62  
#define GS_MBSPM_SET_VAR_32_HANDLE_MSB                63  
#define GS_MBSPM_SET_VAR_32_HANDLE_LSB                64  
#define GS_MBSPM_SET_VAR_32_VAL_MSB                   65  
#define GS_MBSPM_SET_VAR_32_VAL_LSB                   66  
#define GS_MBSPM_GET_VAR_16_HANDLE_MSB                67  
#define GS_MBSPM_GET_VAR_16_HANDLE_LSB                68  
#define GS__BSPM_GET_VAR_16_VAL                       69  /* mirror for write/read */
#define GS_MBSPM_GET_VAR_32_HANDLE_MSB                70  
#define GS_MBSPM_GET_VAR_32_HANDLE_LSB                71  
#define GS__BSPM_GET_VAR_32_VAL_MSB                   72  /* mirror for write/read */
#define GS__BSPM_GET_VAR_32_VAL_LSB                   73  /* mirror for write/read */

#define GS_MBSPM_SET_VAR_16_INDEX_MSB                 80  
#define GS_MBSPM_SET_VAR_16_INDEX_LSB                 81  
#define GS_MBSPM_SET_VAR_32_INDEX_MSB                 82  
#define GS_MBSPM_SET_VAR_32_INDEX_LSB                 83  
#define GS_MBSPM_GET_VAR_16_INDEX_MSB                 84  
#define GS_MBSPM_GET_VAR_16_INDEX_LSB                 85  
#define GS_MBSPM_GET_VAR_32_INDEX_MSB                 86  
#define GS_MBSPM_GET_VAR_32_INDEX_LSB                 87  

#define GS_MBSPM_SET_VAR_32_INDEXED_VAL             2048  /* write once to _MBSPM_SET_VAR_32_INDEX before */
#define GS_MBSPM_SET_VAR_16_INDEXED_VAL             2049  /* write once to _MBSPM_SET_VAR_16_INDEX before */

/* Input Registers: */

#define GS_MBSPM_IS_MASK_ON                            0  /* write once to _MBSPM_MASK_NUMBER before */
#define GS_MBSPM_GET_CURRENT_MASK_SHOWN_MSB            1  
#define GS_MBSPM_GET_CURRENT_MASK_SHOWN_LSB            2  

#define GS_MBSPM_IS_INFO_CONTAINER_ON                 20  /* write once to _MBSPM_INFO_CONTAINER_NUMBER before */
#define GS_MBSPM_IS_MSG_CONTAINER_ON                  21  /* write once to _MBSPM_MSG_CONTAINER_NUMBER before */
#define GS_MBSPM_GET_CURRENT_MSG_CONTAINER_SHOWN_MSB  22  
#define GS_MBSPM_GET_CURRENT_MSG_CONTAINER_SHOWN_LSB  23  

#define GS_MBSPM_IS_KEY_DOWN                          40  /* write once to _MBSPM_KEY_CODE before */
#define GS_MBSPM_IS_ANY_KEY_DOWN                      41  

#define GS_MBSPM_GET_VAR_16_VAL                       60  /* write once to _MBSPM_GET_VAR_16_HANDLE before */
#define GS_MBSPM_GET_VAR_32_VAL_MSB                   61  /* write once to _MBSPM_GET_VAR_32_HANDLE before */
#define GS_MBSPM_GET_VAR_32_VAL_LSB                   62  /* write once to _MBSPM_GET_VAR_32_HANDLE before */

#define GS_MBSPM_GET_VAR_32_INDEXED_VAL             2048  /* write once to _MBSPM_GET_VAR_32_INDEX before */
#define GS_MBSPM_GET_VAR_16_INDEXED_VAL             2049  /* write once to _MBSPM_GET_VAR_16_INDEX before */

/* Coils (Coil status, bits): */

/* not yet used */

/* Input Discrete (input status, input bits): */

#define GS_MBSPM_IS_KEY_PRESSED_0                    200  /* key number 0..255 */
#define GS_MBSPM_IS_KEY_PRESSED_255                  455  /* key number 0..255 */


 /* e m p t y   f i l e */
 /* nothing to generate */

#endif  //_TRMODBUSSLAVE_MSG_H_

