/*****************************************************************************
 * File:  TRQubusMaster_msg.c
 * 
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next build
 * 
 * Description:  Read/Write QuBus configuration values into/from assigned
 *               GDS Designer variables (via thread)
 * 
 ****************************************************************************/

 /* e m p t y   f i l e */
 /* nothing to generate */

