/*****************************************************************************
 * File:  TRQubusMaster_msg.h
 * 
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with next build
 * 
 * Description:  Read/Write QuBus configuration values into/from assigned
 *               GDS Designer variables (via thread)
 * 
 ****************************************************************************/

#ifndef _TRQUBUSMASTER_MSG_H_
#define _TRQUBUSMASTER_MSG_H_

 /* e m p t y   f i l e */
 /* nothing to generate */

#endif  //_TRQUBUSMASTER_MSG_H_

